# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be5c4e50fec55eeb74f437beeea40db75d9aed8239d7f9f8181fbb64033b38be81ea3e81fb145666138325a4107d38b60edfb0ee948537a4ffb987816be5c35

test:
  secret_key_base: 01229716bb1af2922a5e2e784985e878e8632a2e8c9a1b1383100a4a0e4b62594b00a9418309b005f7ec41fde25868d1dcc7e75cdfb14f285f4b464e68537463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
